name: online_exam_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animate_do: any
  dio: any
  injectable: any
  get_it: any
  shared_preferences: any
  flutter_easyloading: any
  equatable: any
  flutter_bloc: any
  pretty_dio_logger: ^1.4.0
  hive: any
  hive_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  mockito: ^5.4.4
  hive_generator: any
  build_runner: any
  flutter_screenutil: any
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto_Condensed-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto/Roboto_Condensed-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto_Condensed-SemiBold.ttf
